### ISSUE TITLE
Questions about quantification

### ISSUE THREAD

**Issue by davidecarlson** [nterhoeven/reper#11]
Hello,
Thanks for creating this tool.  I'm interested in using it compare TE contents (and TE class distribution) among different plant species.  So far it seems to work well (thank you!), but I'm interested in learning a little bit more about how the quantification and landscape methods work. For example, in the repeat-landscape_by-class file, does the numSeqs column represent the estimated number of copies of  a particular class of TE (e.g. Gypsy LTRs) in that genome?  If so, can you explain a bit more about how this is estimated?

Thanks again for providing this tool!
Best,
Dave

**Comment by nterhoeven** [comment]
Hi @davidecarlson 

thanks for your interest in reper. 

I agree, interpreting the output tables is a bit tricky. I will try to explain it:

In general, the most important "thing" is the cluster. I consider a cluster as one "repeat". It consists of several sequences (which do not all have to be "true"). The quantification gives an estimate of how often a sequence of this cluster occurs in the genome. This info is based on the number of reads mapped to sequences from this cluster (column "count" in the output). The idea is similar to expression level analysis used in transcriptomics. 

Each cluster is also assigned a class. The quantification for this class are basically the sums of the clusters with this class. The number of sequences in the class level is not really a reliable result (it is mainly used for calculating the genomic part).

If you want to compare different species, I would recommend to focus on the genomic Part on cluster or class level (depending on the level of detail you are interested in). You can check the R script `plot-landscape.R` for some examples of plotting the results.

**Comment by davidecarlson** [comment]
That helps.  Thanks for your fast reply and explanation!
