### ISSUE TITLE
jellyfish error

### ISSUE THREAD

**Issue by dabitz** [nterhoeven/reper#12]
Mon Jun 22 12:24:31 CEST 2020
running kmerFilter
########################
Can't locate object method "new" via package "jellyfish" at /netscratch/dep_mercier/grp_marques/bin/kmer-scripts/bin/kmer-filter line 254.
########################
kmerFilter failed

**Comment by nterhoeven** [comment]
That looks like a dependency issue.

Are all dependencies installed and working properly? Especially the kmer-filter and the perl5lib-jellyfish?

**Comment by dabitz** [comment]
Yes, they are there.
jellyfish/oldstable 2.2.6-1+b1 amd64
  count k-mers in DNA sequences

libjellyfish-perl/oldstable 2.2.6-1+b1 amd64
  count k-mers in DNA sequences (Perl bindings of jellyfish)

The thing is that in the kmer-filter script, it actually calls for Jellyfish with uppercase J, but the right way should be jellyfish with lowercase j. When I corrected that than it gives me this error...

**Comment by nterhoeven** [comment]
Can you install this perl module: https://github.com/thackl/perl5lib-Jellyfish

This is the one that is supposed to be called by kmer-filter here (uses a capital J)

**Comment by dabitz** [comment]
ok. thanks! It seems to be working now ;)

**Comment by dabitz** [comment]
Not able to find Verbose::ProgressBar

I did not manage to install with cpanm

**Comment by dabitz** [comment]
tried to use Term::ProgressBar instead, but got this error message
Mon Jun 22 15:46:25 CEST 2020
running kmerFilter
########################
[06-22 15:46:25] [kfr] Using binaries: /opt/share/software/bin/jellyfish
[06-22 15:46:26] [kfr] Loading kmer hash
Term::ProgressBar::new We don't handle this many arguments: 6 at blib/lib/Class/MethodMaker/Engine.pm (autosplit into blib/lib/auto/Class/MethodMaker/Engine/new.al) line 957.
[06-22 15:49:05] [kfr] 6058093 distinct kmers loaded
[06-22 15:49:05] [kfr] Filtering: paired end mode
[06-22 15:49:05] [kfr] Files: DP8400009434TL_L01_SP2003170314_1.fastq DP8400009434TL_L01_SP2003170314_1.fastq
########################
kmerFilter failed

**Comment by nterhoeven** [comment]
Verbose is also a custom perl module. You can find it here: https://github.com/BioInf-Wuerzburg/perl5lib-Verbose.git

**Comment by dabitz** [comment]
Thanks! It seems to be working at kmer-filter step now. Hope it will go till the end of the pipeline without interruptions now.

**Comment by nterhoeven** [comment]
Perfect, then I can close this issue
