### ISSUE TITLE
[WIKI] Update test run

### ISSUE THREAD

**Issue by greatfireball** [nterhoeven/reper#6]
Might be worth to update the wiki.

My suggestion is to use the following commands to run the test analysis:

```
# prepare test run
cd test
tar xzf testdata.tar.gz

# set alias for easy execution
alias update_exe_path.sh='sudo docker run --user=$(id -u):$(id -g) -it --rm -v $(pwd):/data --entrypoint update_exe_path.sh reper'
alias reper='sudo docker run --user=$(id -u):$(id -g) -it --rm -v $(pwd):/data reper'

# update the config
update_exe_path.sh reper.conf

# database 
reper configure-refseq
reper configure-REdat

# run the pipeline
reper kmerCount
```

I am running docker via `sudo` to ensure the permission. Via `--user` parameter the owner of the written content is me and not `root`. The `alias` enables calling `reper` and `update_exe_path.sh` as if it would be available via `PATH` variable.

NOTE: Currently the docker-image is still the old image. This workflow require the new image.

**Comment by nterhoeven** [comment]
looks good :-D

I will update it after I merged your pull request

**Comment by nterhoeven** [comment]
I updated the wiki according to the changes from your pull request. I opted for correcting the paths in the testset config file instead of telling the user to run the update-paths-script. Seems mor user friendly to me ;-)
